name: Deploy documentation.js on GitHub pages

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build documentation
        uses: zakodium/documentationjs-action@v1
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: gh-pages
          folder: docs
          clean: true
